### ISSUE TITLE
Frontend - Logs should use backend APIs for pagination and filter

### ISSUE THREAD

**Issue by sebgro98** [sebgro98/Visitation-logger#121]
# Epic: #3

---

## Description
The page for logs uses dummy data and has its own implementation for both pagination and exporting to csv. This should be refactored to use the backend APIs for the aforementioned functionality. 

---

### Tasks
- [x] Refactor pagination to use the backend API to flip pages.
- [x] Implement filtering to use the backend API.
- [x] Refactor exportation locally to a csv-file to use a backend API to fetch all logs which match the filter.

---

## Notes
Additionally, previous issues has implemented a reusable component for tables which can be refactored in this issue aswell. However, it can be extracted to a separate issue as the implementer sees fit.
